### ISSUE TITLE
setuptools-scm-py310 missing dependencies and FTBFS

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#1038]
Trying to install setuptools-scm-py310-6.4.2-1 on my 10.13 box failed:
```
PYTHONPATH=/sw/build.build/setuptools-scm-py310-6.4.2-1/setuptools_scm-6.4.2/src /sw/bin/python3.10 setup.py build
Traceback (most recent call last):
  File "/sw/build.build/setuptools-scm-py310-6.4.2-1/setuptools_scm-6.4.2/setup.py", line 59, in <module>
    setuptools.setup(
  File "/sw/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/sw/lib/python3.10/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/sw/lib/python3.10/site-packages/setuptools/dist.py", line 459, in __init__
    _Distribution.__init__(
  File "/sw/lib/python3.10/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/sw/lib/python3.10/site-packages/setuptools/dist.py", line 836, in finalize_options
    for ep in sorted(loaded, key=by_order):
  File "/sw/lib/python3.10/site-packages/setuptools/dist.py", line 835, in <lambda>
    loaded = map(lambda e: e.load(), filtered)
  File "/sw/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2464, in load
    self.require(*args, **kwargs)
  File "/sw/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2487, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/sw/lib/python3.10/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application
```
That dependency is specified in setup.cfg. So I installed tomli-py310-2.0.1-1, which made setuptools-scm's build stage succeed.

But then the install stage failed:
```
running egg_info
writing src/setuptools_scm.egg-info/PKG-INFO
writing dependency_links to src/setuptools_scm.egg-info/dependency_links.txt
writing entry points to src/setuptools_scm.egg-info/entry_points.txt
writing requirements to src/setuptools_scm.egg-info/requires.txt
writing top-level names to src/setuptools_scm.egg-info/top_level.txt
Traceback (most recent call last):
  File "/sw/build.build/setuptools-scm-py310-6.4.2-1/setuptools_scm-6.4.2/setup.py", line 59, in <module>
    setuptools.setup(
  File "/sw/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/sw/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/sw/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/sw/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/sw/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
    return orig.install.run(self)
  File "/sw/lib/python3.10/distutils/command/install.py", line 580, in run
    self.run_command(cmd_name)
  File "/sw/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/sw/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/sw/lib/python3.10/site-packages/setuptools/command/install_egg_info.py", line 34, in run
    self.run_command('egg_info')
  File "/sw/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/sw/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/sw/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 299, in run
    self.find_sources()
  File "/sw/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
    mm.run()
  File "/sw/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 541, in run
    self.add_defaults()
  File "/sw/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 581, in add_defaults
    rcfiles = list(walk_revctrl())
  File "/sw/lib/python3.10/site-packages/setuptools/command/sdist.py", line 18, in walk_revctrl
    for item in ep.load()(dirname):
  File "/sw/build.build/setuptools-scm-py310-6.4.2-1/setuptools_scm-6.4.2/src/setuptools_scm/integration.py", line 79, in find_files
    for ep in iter_entry_points("setuptools_scm.files_command"):
  File "/sw/build.build/setuptools-scm-py310-6.4.2-1/setuptools_scm-6.4.2/src/setuptools_scm/utils.py", line 144, in iter_entry_points
    return iter_entry_points(*k, **kw)
  File "/sw/build.build/setuptools-scm-py310-6.4.2-1/setuptools_scm-6.4.2/src/setuptools_scm/_entrypoints.py", line 51, in iter_entry_points
    all_eps = entry_points()
  File "/sw/lib/python3.10/importlib/metadata/__init__.py", line 1009, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/sw/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
    ordered = sorted(eps, key=by_group)
  File "/sw/lib/python3.10/importlib/metadata/__init__.py", line 1006, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/sw/lib/python3.10/importlib/metadata/_itertools.py", line 15, in unique_everseen
    for element in iterable:
  File "/sw/lib/python3.10/importlib/metadata/__init__.py", line 565, in <genexpr>
    resolver(context) for resolver in cls._discover_resolvers()
  File "/sw/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 411, in find_distributions
    found = self._search_paths(context.pattern, context.path)
AttributeError: 'Context' object has no attribute 'pattern'
```
Googling around, this seems to have something to do with certain versions of importlib-metadata-pyXXX; I have our current 1.1.3-1 installed,

**Comment by dhomeier** [comment]
What happens if you uninstall `importlib-metadata-py310` first? I have a note that it was required to build the py37 version of recent setuptools-scm, but on 12.6 the py310 build completes either with or without it installed; my build continues as
```
writing top-level names to src/setuptools_scm.egg-info/top_level.txt
listing git files failed - pretending there aren't any
reading manifest file 'src/setuptools_scm.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '*.nix'
warning: no previously-included files found matching '.pre-commit-config.yaml'
adding license file 'LICENSE'
writing manifest file 'src/setuptools_scm.egg-info/SOURCES.txt'
Copying src/setuptools_scm.egg-info to /opt/sw/src/fink.build/root-setuptools-scm-py310-6.4.2-1/opt/sw/lib/python3.10/site-packages/setuptools_scm-6.4.2-py3.10.egg-info
running install_scripts
```

**Comment by dmacks** [comment]
Removing importlib-metadata-py310 (1.1.3-1) allowed setuptools-scm-py310 (6.4.2-1) to build. I'll check the other pyXXX...

**Comment by dmacks** [comment]
importlib-metadata-pyXX is just broken itself. Can't even build it anymore (I had debs laying around, no idea what changed). But now I get the same AttributeError, in /sw/build.build/importlib-metadata-py310-1.1.3-1/importlib_metadata-1.1.3/importlib_metadata/__init__.py, and likewise in py{38,39} but succeeds in py{36,37} even though it's the same version. So it must be some dependency has changed. I'll look at updating importlib-metadata-pyXX

**Comment by dhomeier** [comment]
The fink version is ancient indeed, and it BDeps on setuptools-scm-pyXX itself. Nonetheless I could still rebuild it for py310 (which only has setuptools-tng-py as other BDep and zipp-py as Dep, both installed in their current Fink versions 59.6.0 and 0.6.0).The current upstream for >= py37 is 6.7.0 however; got an update for that, but I haven't checked the dependence chain so far...

**Comment by nieder** [comment]
importlib-metadata-py37+ was updated to 6.7.0 with 2b3a763beb986d2b22b4571b203a3aa7ab7f86ef on Jul 28, 2023. Closing this unless shown to still fail (and the tomli missing Dep was also fixed).
