### ISSUE TITLE
libtalloc2-2.1.16-1: waf fails with: AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by cooljeanius** [fink/fink-distributions#1093]
Possibly some sort of python version incompatibility?
```
[ -x /usr/bin/python3 ] && pyversion=3 ; PYTHON=/usr/bin/python$pyversion make -w
make: Entering directory '/opt/sw/src/fink.build/libtalloc2-2.1.16-1/talloc-2.1.16'
PYTHONHASHSEED=1 WAF_MAKE=1 /usr/bin/python3 `PATH=buildtools/bin:../../buildtools/bin:$PATH which waf` build
Waf: Entering directory `/opt/sw/src/fink.build/libtalloc2-2.1.16-1/talloc-2.1.16/bin/default'
Traceback (most recent call last):
  File "/opt/sw/src/fink.build/libtalloc2-2.1.16-1/talloc-2.1.16/third_party/waf/waflib/Scripting.py", line 158, in waf_entry_point
    run_commands()
  File "/opt/sw/src/fink.build/libtalloc2-2.1.16-1/talloc-2.1.16/third_party/waf/waflib/Scripting.py", line 251, in run_commands
    ctx = run_command(cmd_name)
  File "/opt/sw/src/fink.build/libtalloc2-2.1.16-1/talloc-2.1.16/third_party/waf/waflib/Scripting.py", line 235, in run_command
    ctx.execute()
  File "/opt/sw/src/fink.build/libtalloc2-2.1.16-1/talloc-2.1.16/third_party/waf/waflib/Scripting.py", line 573, in execute
    return execute_method(self)
  File "/opt/sw/src/fink.build/libtalloc2-2.1.16-1/talloc-2.1.16/third_party/waf/waflib/Build.py", line 231, in execute
    self.execute_build()
  File "/opt/sw/src/fink.build/libtalloc2-2.1.16-1/talloc-2.1.16/third_party/waf/waflib/Build.py", line 245, in execute_build
    self.pre_build()
  File "/opt/sw/src/fink.build/libtalloc2-2.1.16-1/talloc-2.1.16/third_party/waf/waflib/Build.py", line 542, in pre_build
    m(self)
  File "./buildtools/wafsamba/samba_deps.py", line 1106, in check_project_rules
    tstart = time.clock()
AttributeError: module 'time' has no attribute 'clock'
make: *** [Makefile:8: all] Error 2
make: Leaving directory '/opt/sw/src/fink.build/libtalloc2-2.1.16-1/talloc-2.1.16'
### execution of [ failed, exit code 2
### execution of /tmp/fink.hjye4 failed, exit code 2
Removing runtime build-lock...
Removing build-lock package...
/opt/sw/bin/dpkg-lockwait -r fink-buildlock-libtalloc2-2.1.16-1
(Reading database ... 
dpkg: serious warning: files list file for package `fink-buildlock-ccp4-6.5-1' missing, assuming package has no files currently installed.
1029180 files and directories currently installed.)
Removing fink-buildlock-libtalloc2-2.1.16-1 ...
```
I'm on x86_64 Big Sur with Xcode 13. cc @danielj7

**Comment by nieder** [comment]
The proximate cause is that `time.clock` has been deprecated since python3.3 and apparently finally removed in python3.8 (which I think is what system-python is in Big Sur).

There's newer libtalloc upstream, but looks like it's python3 only. This is on 10.14 using system-python2:
```
Traceback (most recent call last):
  File "/sw/build.build/libtalloc2-2.4.1-1/talloc-2.4.1/third_party/waf/waflib/Scripting.py", line 141, in waf_entry_point
    set_main_module(wscript)
  File "/sw/build.build/libtalloc2-2.4.1-1/talloc-2.4.1/third_party/waf/waflib/Scripting.py", line 191, in set_main_module
    Context.g_module = Context.load_module(file_path)
  File "/sw/build.build/libtalloc2-2.4.1-1/talloc-2.4.1/third_party/waf/waflib/Context.py", line 682, in load_module
    exec(compile(code, path, 'exec'), module.__dict__)
  File "/sw/build.build/libtalloc2-2.4.1-1/talloc-2.4.1/wscript", line 17, in <module>
    import wafsamba
  File "./buildtools/wafsamba/wafsamba.py", line 15, in <module>
    from samba_autoconf import *
  File "./buildtools/wafsamba/samba_autoconf.py", line 356
    f'static int test_array[1 - 2 * !((({v})-1) {op} 0)];',
                                                         ^
SyntaxError: invalid syntax
```

With current libtalloc2, does adding the following code to `/opt/sw/fink/dists/stable/main/finkinfo/libs/libtalloc2.info` help?
```
PatchScript: <<
	[ -x /usr/bin/python3 ] && perl -pi -e 's|time.clock|time.perf_counter|g' buildtools/wafsamba/samba_deps.py || echo "Using python2"
<<
```

**Comment by nieder** [comment]
Never mind about the test. I've updated to a newer version that works as is.

**Comment by cooljeanius** [comment]
> Never mind about the test. I've updated to a newer version that works as is.

OK, thanks, confirming that it's fixed! Of course, now I'm seeing a similar error from libtevent0 next...

**Comment by cooljeanius** [comment]
> > Never mind about the test. I've updated to a newer version that works as is.
> 
> OK, thanks, confirming that it's fixed! Of course, now I'm seeing a similar error from libtevent0 next...

(ok, I've opened #1095 for that now...)
