### ISSUE TITLE
idna-py 2.7 egg-info permissions still broken

### ISSUE THREAD

**Issue by dhomeier** [fink/fink-distributions#211]
`idna-py-2.7-1` is installing files in `%p/lib/python%type_raw[python]/site-packages/idna-2.7-py%type_raw[python].egg-info` with permissions 700:
```
> ls -lF /sw/lib/python3.5/site-packages/idna-2.7-py3.5.egg-info/                                                                                      
total 48
-rw-r--r--  1 root  admin  10565 30 Jul 17:45 PKG-INFO
-rwx------  1 root  admin    529 30 Jul 17:45 SOURCES.txt*
-rwx------  1 root  admin      1 30 Jul 17:45 dependency_links.txt*
-rwx------  1 root  admin      5 30 Jul 17:45 top_level.txt*
```
This breaks e.g. pip:
```
> sudo -u fink-bld HOME=$PWD /sw/bin/pip-py3.5 freeze                                                                                              
Exception:
Traceback (most recent call last):
  File "/sw/lib/python3.5/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/sw/lib/python3.5/site-packages/pip/_internal/commands/freeze.py", line 93, in run
    for line in freeze(**freeze_kwargs):
  File "/sw/lib/python3.5/site-packages/pip/_internal/operations/freeze.py", line 42, in freeze
    dist.get_metadata_lines('dependency_links.txt')
  File "/sw/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1408, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/sw/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1404, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/sw/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1516, in _get
    with open(path, 'rb') as stream:
PermissionError: [Errno 13] Permission denied: '/sw/lib/python3.5/site-packages/idna-2.7-py3.5.egg-info/dependency_links.txt'
```
The .info is already fixing this for `PKG-INFO`, but not for the other files.

**Comment by danielj7** [comment]
Fixed for real this time. There is an upstream bug: https://github.com/kjd/idna/issues/66
