### ISSUE TITLE
u-msgpack-py3{4-6} tests fail when LANG is not set

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#326]
````python
PYTHONPATH=/sw/build.build/u-msgpack-py36-2.5.0-1/u-msgpack-python-2.5.0 /sw/bin/python3.6 test_umsgpack.py || exit 2
..	Testing fix raw: object b''
	Testing fix raw: object ''
<snip>
E..	Testing fix raw: object b''
<snip>
E
======================================================================
ERROR: test_pack_single (__main__.TestUmsgpack)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_umsgpack.py", line 389, in test_pack_single
    (name, obj_repr if len(obj_repr) < 24 else obj_repr[0:24] + "..."))
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 41: ordinal not in range(128)

======================================================================
ERROR: test_unpack_single (__main__.TestUmsgpack)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_umsgpack.py", line 414, in test_unpack_single
    (name, obj_repr if len(obj_repr) < 24 else obj_repr[0:24] + "..."))
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 41: ordinal not in range(128)

----------------------------------------------------------------------
Ran 19 tests in 0.374s

FAILED (errors=2)
````
This failure happens with py34, py35, and py36.  py27 and py37 pass.

If I add LANG=en_US.UTF-8 to front of the TestScript command, then tests pass for all python variants.

**Comment by danielj7** [comment]
Thanks! Now fixed in https://github.com/fink/fink-distributions/commit/1860f403677cdafbe0d1a7960cccae36b0981d0d
