### ISSUE TITLE
pipdeptree broken with pip-py-18.1

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#327]
The update to pip-py %v=18.1 broke pipdeptree.
````bash
nieder $ pipdeptree3.5
Traceback (most recent call last):
  File "/sw/lib/python3.5/site-packages/pipdeptree.py", line 17, in <module>
    from pip._internal import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sw/bin/pipdeptree3.5", line 11, in <module>
    load_entry_point('pipdeptree==0.13.0', 'console_scripts', 'pipdeptree')()
  File "/sw/lib/python3.5/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/sw/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2707, in load_entry_point
    return ep.load()
  File "/sw/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/sw/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/sw/lib/python3.5/site-packages/pipdeptree.py", line 20, in <module>
    from pip import get_installed_distributions, FrozenRequirement
ImportError: cannot import name 'get_installed_distributions'
````
https://github.com/pypa/pip/issues/5154
Supposedly fixed in pipdeptree 0.13.1 naiquevin/pipdeptree#105

**Comment by kamischi** [comment]
issue is fixed.
