### ISSUE TITLE
psutil-pyXX has no files

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#349]
psutil-py only installs DocFiles. It has no actual python files.
````
$ dpkg-deb -c /sw/fink/debs/psutil-py36_5.4.7-1_darwin-x86_64.deb 
drwxr-xr-x root/admin        0 2019-02-10 22:29 ./
drwxr-xr-x root/admin        0 2019-02-10 22:29 ./sw/
drwxr-xr-x root/admin        0 2019-02-10 22:29 ./sw/share/
drwxr-xr-x root/admin        0 2019-02-10 22:29 ./sw/share/doc/
drwxr-xr-x root/admin        0 2019-02-10 22:29 ./sw/share/doc/psutil-py36/
-rw-r--r-- root/admin     8589 2019-02-10 22:29 ./sw/share/doc/psutil-py36/CREDITS
-rw-r--r-- root/admin     6390 2019-02-10 22:29 ./sw/share/doc/psutil-py36/DEVGUIDE.rst
-rw-r--r-- root/admin   150500 2019-02-10 22:29 ./sw/share/doc/psutil-py36/HISTORY.rst
-rw-r--r-- root/admin     5381 2019-02-10 22:29 ./sw/share/doc/psutil-py36/IDEAS
-rw-r--r-- root/admin     3749 2019-02-10 22:29 ./sw/share/doc/psutil-py36/INSTALL.rst
-rw-r--r-- root/admin     1584 2019-02-10 22:29 ./sw/share/doc/psutil-py36/LICENSE
-rw-r--r-- root/admin    26218 2019-02-10 22:29 ./sw/share/doc/psutil-py36/PKG-INFO
-rw-r--r-- root/admin    19917 2019-02-10 22:29 ./sw/share/doc/psutil-py36/README.rst
````
If I replace the current InstallScript with `%p/bin/python%type_raw[python] setup.py install --root %d`, then I get actual python files installed into the deb.

**Comment by dhomeier** [comment]
Same here. Also, calling the Python script for the tests directly seems to get around some of the failures and obviates the need for the patches (which no longer work with the latest upstream 5.6.1).

**Comment by kamischi** [comment]
I had a go with version 5.6.1 and proceeded as written in INSTALL without the previous patches and these scripts:

`CompileScript: %p/bin/python%type_raw[python] setup.py build`

`InstallScript: %p/bin/python%type_raw[python] setup.py install --root %d`

It looked ok, but the test (`python%type_raw[python] test`) failed with:

```
...
psutil.tests.test_windows.TestSystemAPIs.test_total_phymem ... skipped 'WINDOWS only'

======================================================================
ERROR: psutil.tests.test_contracts.TestDeprecations.test_memory_info_ex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sw/src/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/psutil/tests/test_contracts.py", line 185, in test_memory_info_ex
    w = ws[0]
IndexError: list index out of range
...
```

**Comment by dhomeier** [comment]
You mean `%p/bin/python%type_raw[python] setup.py test`?
That created an infinite loop for me, while I only see the `test_memory_info_ex` error above with py27, but the same other 7-8 failures I saw in my setup. Was this with an existing version of the package installed?

I found that `setup.py build` seemed to fail to correctly build (or at least install in in `build/lib*`) the `OS X` extension:
```
Traceback (most recent call last):
  File "/sw/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/sw/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/psutil/__init__.py", line 151, in <module>
    from . import _psosx as _psplatform
  File "/scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/psutil/_psosx.py", line 16, in <module>
    from . import _psutil_osx as cext
ImportError: cannot import name '_psutil_osx'
```
When sticking to the old `CompileScript: make build PYTHON=%p/bin/python%type_raw[python]` this seemed to work, although I found for the best test results I needed both the build and the source directory in `PYTHONPATH`...
```
TestScript: <<
    #!/bin/sh -ev
    export LC_CTYPE=en_US.UTF-8 PYTHONPATH=$(ls -d %b/build/lib.macosx-*-%type_raw[python]):%b
    # follow link to actual binary for python3.Xm versions
    PYTHON=$(ls -l %p/bin/python%type_raw[python] | awk '{print $NF}')
    # 4 failures, 1 error on Python2.7, 7 failures on Python3
    PYTHONWARNINGS=all PSUTIL_TESTING=1 PSUTIL_DEBUG=1 $PYTHON -B -m psutil.tests || echo 'Test failures'
    find build -name '*.pyc' -delete
  <<
```
Except for one, the remaining failures seem Unicode-related, with the 3 additional ones in Python3 not even identifiable by eye (3x this same error):
```
AssertionError: '/scr[20 chars]ild/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-28254-ƒőő2' != '/scr[20 chars]ild/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-28254-ƒőő2'
- /scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-28254-ƒőő2
?                                                                                  ^^^^
+ /scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-28254-ƒőő2
?                                                                                  ^^
```
So they don't look too serious to me, but if your version had no other failures at all, maybe it's worth working on that...

**Comment by dhomeier** [comment]
For reference, with no `psutil-py36` previously installed:
```
======================================================================
FAIL: psutil.tests.test_process.TestProcess.test_zombie_process
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/psutil/tests/test_process.py", line 1381, in test_zombie_process
    self.assertIn(zpid, psutil.pids())
AssertionError: 30956 not found in [0, 1, 52, 53, 55, 56, 57, 59, 60, 62, 63, 65, 66, 71, 74, 76, 78, 82, 83, 84, 88, 89, 92, 95, 96, 98, 99, 100, 101, 102, 104, 106, 107, 108, 109, 111, 113, 114, 115, 116, 119, 120, 121, 123, 126, 127, 141, 161, 163, 166, 169, 177, 178, 179, 185, 186, 192, 197, 199, 210, 211, 212, 213, 222, 223, 235, 251, 258, 259, 260, 265, 266, 267, 273, 277, 281, 284, 295, 301, 302, 303, 304, 305, 306, 307, 308, 309, 311, 312, 313, 314, 315, 316, 317, 327, 328, 330, 331, 333, 347, 348, 350, 351, 352, 353, 354, 363, 364, 366, 375, 376, 389, 390, 411, 415, 416, 419, 440, 442, 451, 458, 462, 464, 466, 469, 471, 472, 474, 475, 476, 477, 479, 480, 481, 482, 484, 485, 486, 487, 488, 489, 490, 491, 493, 494, 497, 498, 500, 501, 502, 504, 505, 508, 509, 510, 511, 512, 513, 514, 515, 521, 522, 523, 524, 525, 528, 530, 532, 533, 537, 540, 542, 545, 547, 548, 549, 550, 552, 553, 554, 555, 556, 557, 560, 561, 562, 563, 564, 565, 566, 569, 571, 572, 573, 574, 576, 577, 578, 579, 580, 581, 607, 608, 628, 629, 630, 652, 654, 655, 662, 664, 666, 670, 671, 701, 702, 705, 746, 747, 752, 811, 850, 933, 937, 1076, 1180, 1181, 1182, 1199, 1213, 1247, 1274, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 1381, 1382, 1420, 1421, 1423, 1442, 1457, 1474, 1478, 1479, 1514, 1515, 1579, 1580, 1581, 1584, 1592, 1597, 1598, 1599, 1600, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1614, 1615, 1616, 1617, 1619, 1626, 1629, 1630, 1640, 1641, 1644, 1646, 1647, 1648, 1652, 1653, 1654, 1656, 1657, 1664, 1666, 1667, 1668, 1670, 1671, 1674, 1675, 1679, 1686, 1687, 1695, 1830, 1855, 1856, 1862, 1878, 1879, 1883, 1885, 1893, 1911, 1917, 1919, 1979, 1980, 1982, 1990, 1994, 3226, 3227, 3228, 3231, 3232, 3233, 3239, 3242, 3243, 3244, 3245, 3251, 3253, 3254, 4927, 5677, 5678, 5686, 5797, 5868, 5942, 5948, 5958, 5959, 5990, 5991, 6534, 6535, 6536, 6554, 8503, 8563, 8644, 8665, 8691, 8717, 8735, 8742, 8750, 9768, 10019, 10020, 10512, 10517, 10526, 10527, 10528, 10917, 12294, 12295, 12628, 12659, 12660, 12921, 12923, 13036, 13054, 13055, 13352, 13353, 15021, 15170, 16403, 16404, 16412, 16416, 16417, 16434, 16435, 16440, 17267, 17268, 17651, 17653, 20139, 20489, 20490, 20491, 20492, 20507, 20640, 20712, 21198, 22551, 22552, 23221, 23222, 23223, 23224, 23965, 24829, 26079, 26080, 27043, 27045, 27047, 27049, 27091, 28352, 28388, 28690, 28691, 28692, 28693, 28694, 28699, 28700, 28701, 28705, 28819, 28960, 29784, 29785, 29786, 29787, 29788, 29789, 29790, 30533, 30534, 30535, 30536, 30791, 30798, 30799, 30800, 30805, 30831, 30832, 30955, 32585, 38259, 39853, 39860, 41042, 41043, 41044, 45537, 45538, 45550, 45551, 45788, 46130, 46160, 46163, 46192, 46200, 46203, 46225, 47078, 60463, 62680, 68607, 68693, 70742, 73062, 73070, 73072, 73073, 80318, 81165, 81250, 81252, 81259, 81386, 81744, 81989, 82208, 82903, 83184, 83199, 83207, 83340, 83728, 83877, 83955, 83977, 84055, 84056, 84057, 84058, 84190, 84326, 85000, 85476, 85617, 85968, 85990, 86012, 86013, 92949, 92950, 94778, 94985, 95010, 95036, 95363, 96323]

======================================================================
FAIL: psutil.tests.test_unicode.TestFSAPIs.test_proc_cwd
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/psutil/tests/test_unicode.py", line 205, in test_proc_cwd
    self.assertEqual(cwd, dname)
AssertionError: '/scr[20 chars]ild/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805-ƒőő2' != '/scr[20 chars]ild/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805-ƒőő2'
- /scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805-ƒőő2
?                                                                                  ^^^^
+ /scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805-ƒőő2
?                                                                                  ^^


======================================================================
FAIL: psutil.tests.test_unicode.TestFSAPIs.test_proc_exe
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/psutil/tests/test_unicode.py", line 169, in test_proc_exe
    self.assertEqual(exe, self.funky_name)
AssertionError: '/scr[19 chars]uild/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805-ƒőő' != '/scr[19 chars]uild/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805-ƒőő'
- /scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805-ƒőő
?                                                                                  ^^^^
+ /scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805-ƒőő
?                                                                                  ^^


======================================================================
FAIL: psutil.tests.test_unicode.TestFSAPIs.test_proc_open_files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/psutil/tests/test_unicode.py", line 219, in test_proc_open_files
    os.path.normcase(self.funky_name))
AssertionError: '/scr[19 chars]uild/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805-ƒőő' != '/scr[19 chars]uild/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805-ƒőő'
- /scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805-ƒőő
?                                                                                  ^^^^
+ /scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805-ƒőő
?                                                                                  ^^


======================================================================
FAIL: psutil.tests.test_unicode.TestFSAPIsWithInvalidPath.test_proc_cwd
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/psutil/tests/test_unicode.py", line 205, in test_proc_cwd
    self.assertEqual(cwd, dname)
AssertionError: '/scr[27 chars]til-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805f%C0%802' != '/scr[27 chars]til-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805f\udcc0\udc802'
- /scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805f%C0%802
?                                                                                 ^^^^^^
+ /scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805f\udcc0\udc802
?                                                                                 ^^


======================================================================
FAIL: psutil.tests.test_unicode.TestFSAPIsWithInvalidPath.test_proc_exe
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/psutil/tests/test_unicode.py", line 169, in test_proc_exe
    self.assertEqual(exe, self.funky_name)
AssertionError: '/scr[26 chars]util-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805f%C0%80' != '/scr[26 chars]util-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805f\udcc0\udc80'
- /scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805f%C0%80
?                                                                                 ^^^^^^
+ /scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805f\udcc0\udc80
?                                                                                 ^^


======================================================================
FAIL: psutil.tests.test_unicode.TestFSAPIsWithInvalidPath.test_proc_open_files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/psutil/tests/test_unicode.py", line 219, in test_proc_open_files
    os.path.normcase(self.funky_name))
AssertionError: '/scr[26 chars]util-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805f%C0%80' != '/scr[26 chars]util-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805f\udcc0\udc80'
- /scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805f%C0%80
?                                                                                 ^^^^^^
+ /scratch.noindex/fink.build/psutil-py36-5.6.1-1/psutil-5.6.1/@psutil-test-30805f\udcc0\udc80
?                                                                                 ^^


----------------------------------------------------------------------
Ran 534 tests in 9.131s

FAILED (failures=7, skipped=250)
```
