### ISSUE TITLE
pil-py build failure

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#429]
pil-py has `--disable-platform-guessing`, but this breaks the build for pil-py34 (27, 35-37 are all OK). This is on 10.13, but am getting similar problems on 10.14.
```
	if [ "$(uname -r | cut -d. -f1)" -ge 17 ]; then
		SDK_PATH="$(xcrun --sdk macosx --show-sdk-path)"
		ZLIB_ROOT="$SDK_PATH/usr" CFLAGS="-Wno-nullability-completeness -Wno-expansion-to-defined" /sw/bin/python3.4 setup.py build_ext --disable-platform-guessing
	else
		ZLIB_ROOT="/usr" /sw/bin/python3.4 setup.py build_ext --disable-platform-guessing
	fi
uname -r | cut -d. -f1
xcrun --sdk macosx --show-sdk-path
running build_ext


The headers or library files could not be found for zlib,
a required dependency when compiling Pillow from source.

Please see the install instructions at:
   https://pillow.readthedocs.io/en/latest/installation.html

Traceback (most recent call last):
  File "setup.py", line 800, in <module>
    zip_safe=not (debug_build() or PLATFORM_MINGW), )
  File "/sw/lib/python3.4/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/sw/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/sw/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/sw/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/sw/lib/python3.4/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "setup.py", line 612, in build_extensions
    raise RequiredDependencyException(f)
__main__.RequiredDependencyException: zlib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 812, in <module>
    raise RequiredDependencyException(msg)
__main__.RequiredDependencyException: 

The headers or library files could not be found for zlib,
a required dependency when compiling Pillow from source.

Please see the install instructions at:
   https://pillow.readthedocs.io/en/latest/installation.html
```
If I remove the --disable-platform-guessing flag, then the build succeeds, but I need to make sure to get it out in the various *Scripts.

There are some other bits on 10.14 that also need to be fixed re:SDK_PATH to fully work on 10.14.
v5.4.1 is the last version that supports py34. Latest is py27 and py35+.

**Comment by danielj7** [comment]
I'll take a look at this soon. I've been out of things for a while and need to get my system working properly after the great 10.14.5 debacle.

**Comment by danielj7** [comment]
This should be fixed now. Let me know if there are any other problems.
