### ISSUE TITLE
obspy-core tries to fetch distribute pymod in CompileScript

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#81]
@schwehr 
````
python2.7 setup.py build
Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
Traceback (most recent call last):
  File "setup.py", line 166, in <module>
    setupPackage()
  File "setup.py", line 123, in setupPackage
    distribute_setup.use_setuptools()
  File "/sw/build.build/obspy-core-py27-0.7.1-1/obspy.core-0.7.1/distribute_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/sw/build.build/obspy-core-py27-0.7.1-1/obspy.core-0.7.1/distribute_setup.py", line 124, in _do_download
    to_dir, download_delay)
  File "/sw/build.build/obspy-core-py27-0.7.1-1/obspy.core-0.7.1/distribute_setup.py", line 193, in download_setuptools
    src = urlopen(url)
  File "/sw/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/sw/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/sw/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/sw/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/sw/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/sw/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: SSL is required
````
distribute has been replaced by setuptools-tng, and I thought the two were interchangeable, but apparently the code might need some tweaking to find setutools instead of distribute.

This patch lets it build with setuptools:
````
	perl -pi -e 's|import distribute_setup|import setuptools|g' setup.py
	perl -pi -e 's|distribute_setup.use_setuptools|#distribute_setup.use_setuptools|g' setup.py
````
Lastly, latest upstream is %v=1.1.0.

**Comment by schwehr** [comment]
Feel free to change the package as required.  I've pretty much had to stop spending time on fink :(

This seems okay.  I'm not sure why it is pulling the ancient distribute.  Perhaps this old version of obspy is borked.  Downloading packages from build does not seem okay

    Depends: python%type_pkg[python], scipy-py%type_pkg[python], numpy-py%type_pkg[python]
    BuildDepends: setuptools-tng-py%type_pkg[python]

**Comment by nieder** [comment]
Many pymods try to grab missing deps if not present. This was a really old version that still looked for distribute, and I get the feeling that our current setuptools-tng dropped the compatibility layer that made things looking for distribute use setuptools. Fixed for now.
