### ISSUE TITLE
libnss3-3.62-6 needs xcode.app BDep

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#865]
On 12.1 with only the CLT installed:
```
nss-3.62/nss/tests/tools/tools.sh
nss-3.62/nss/trademarks.txt
sudo -u fink-bld [ENV] sh -c /tmp/fink.iZEno
[ -r /opt/sw/fink/dists/stable/main/finkinfo/crypto/libnss3.patch ]
sudo -u fink-bld [ENV] sh -c /tmp/fink.TvcC7
/usr/bin/patch -p1 < /opt/sw/fink/dists/stable/main/finkinfo/crypto/libnss3.patch
patching file nss/pkg/pkg-config/nss-config.in
patching file nss/pkg/pkg-config/nss.pc.in
perl -pi -e 's,\@executable_path,/opt/sw/lib/nss3,g' nss/coreconf/Darwin.mk nss/lib/freebl/config.mk nss/coreconf/config.gypi
sudo -u fink-bld [ENV] sh -c /tmp/fink.NtNHt
/tmp/fink.a7h_N
#!/bin/sh -ev
	pushd nss
/opt/sw/build.build/libnss3-3.62-6/nss-3.62/nss /opt/sw/build.build/libnss3-3.62-6/nss-3.62
	./build.sh \
		--with-nspr=/opt/sw/include/nspr:/opt/sw/lib/nspr \
		--system-sqlite \
		-v
run_scanbuild gyp -f ninja --depth=/opt/sw/build.build/libnss3-3.62-6/nss-3.62/nss --generator-output=. -Dnspr_include_dir=/opt/sw/include/nspr -Dnspr_lib_dir=/opt/sw/lib/nspr -Duse_system_sqlite=1 -Dtarget_arch=x64 -Denable_sslkeylogfile=1 -Dnss_dist_dir=/opt/sw/build.build/libnss3-3.62-6/nss-3.62/dist -Dnss_dist_obj_dir=/opt/sw/build.build/libnss3-3.62-6/nss-3.62/dist/Debug /opt/sw/build.build/libnss3-3.62-6/nss-3.62/nss/nss.gyp
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/opt/sw/bin/gyp", line 11, in <module>
    load_entry_point('gyp==0.1', 'console_scripts', 'gyp')()
  File "/opt/sw/lib/python2.7/site-packages/gyp/__init__.py", line 552, in script_main
    return main(sys.argv[1:])
  File "/opt/sw/lib/python2.7/site-packages/gyp/__init__.py", line 545, in main
    return gyp_main(args)
  File "/opt/sw/lib/python2.7/site-packages/gyp/__init__.py", line 530, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/opt/sw/lib/python2.7/site-packages/gyp/generator/ninja.py", line 2493, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "/opt/sw/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/opt/sw/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'groups'
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

**Comment by dmacks** [comment]
Looks like it's gyp-pyXX that is the origin/direct caller of `xcodebuild`; should the dependency be there instead

**Comment by nieder** [comment]
probably.

**Comment by dmacks** [comment]
Does rebuilding gyp-py27 give any relevant diagnostic?

**Comment by nieder** [comment]
Rebuilding gyp-py27 doesn't show any useful details, just the usual copying and byte-compiling from setuptools.

**Comment by dmacks** [comment]
I don't know a thing about the gyp tool, so if someone wants to push a `RuntimeDepends:xcode.app` into it (maybe while updating it to a newer upstream?) I'll leave that to them.
