### ISSUE TITLE
docutils-py-0.14 doesn't build on macOS12

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#931]
The latest sets of macOS no longer ship with /usr/bin/python (v2). During build phase, this command:
```
PYTHONPATH=..:../docutils/utils ../tools/rst2html.py $i $htmldoc
```
tries to run with `#!/usr/bin/env python`, which fails. Forcing it to use `%p/bin/python%type_pkg[python]` fails with this error for at least python3.7 (earliest I can try with macOS 12.6):
```
Making BUGS.html
Traceback (most recent call last):
  File "tools/rst2html.py", line 17, in <module>
    from docutils.core import publish_cmdline, default_description
  File "/opt/sw/build.build/docutils-py37-0.15-1/docutils-0.15/docutils/__init__.py", line 91, in <module>
    class ApplicationError(StandardError): pass
NameError: name 'StandardError' is not defined
```
There's newer docutils releases that indicate native support for newer versions of python.

**Comment by dmacks** [comment]
It's a pretty notable bug, a -pyXX tied to a fink pythonXX language pakage trying to use a python other than fink's interp specific to that XX.

**Comment by dmacks** [comment]
Here's how to fix bug I noted: [correct-python-interp.patch](https://github.com/fink/fink-distributions/files/10299210/correct-python-interp.patch)

It should fix FTBFS for -py27 on all platforms, and trigger FTBFS for -py3X on all platforms, so now it's all consistent, and should be incorporated into any future packaging if *Script need to run those .py scripts

**Comment by dmacks** [comment]
[This](https://sourceforge.net/p/docutils/code/8348) is the key upstream patch that claims to fix for python3 compat. It does change the 'StandardError' as mentioned in the original error message.

**Comment by dmacks** [comment]
Latest upstream 0.19 fails for all pythons I tried (-py27, -py34, -py310), each in a totally different way. I'm out.

**Comment by TheSin-** [comment]
any progress on this I need docutils-py3xx

Has anyone looked at @dhomeier fixes so we can accept them?
