### ISSUE TITLE
Failed: phase installing: setuptools-tng-py27-44.1.1-1 failed

### ISSUE THREAD

**Issue by dak180** [fink/fink-distributions#976]
```
Setting runtime build-lock...
dpkg-deb -b /opt/sw/src/fink.build/root-fink-buildlock-setuptools-tng-py27-44.1.1-1 /opt/sw/src/fink.build
dpkg-deb: building package 'fink-buildlock-setuptools-tng-py27-44.1.1-1' in '/opt/sw/src/fink.build/fink-buildlock-setuptools-tng-py27-44.1.1-1_2023.01.30-20.36.26_darwin-arm64.deb'.
Installing build-lock package...
/opt/sw/bin/dpkg-lockwait -i /opt/sw/src/fink.build/fink-buildlock-setuptools-tng-py27-44.1.1-1_2023.01.30-20.36.26_darwin-arm64.deb
Selecting previously unselected package fink-buildlock-setuptools-tng-py27-44.1.1-1.
(Reading database ... 74279 files and directories currently installed.)
Preparing to unpack .../fink-buildlock-setuptools-tng-py27-44.1.1-1_2023.01.30-20.36.26_darwin-arm64.deb ...
Unpacking fink-buildlock-setuptools-tng-py27-44.1.1-1 (2023.01.30-20.36.26) ...
Setting up fink-buildlock-setuptools-tng-py27-44.1.1-1 (2023.01.30-20.36.26) ...
sudo -u fink-bld [ENV] sh -c /tmp/fink.ndsXj
unzip -o /opt/sw/src/setuptools-44.1.1.zip
Archive:  /opt/sw/src/setuptools-44.1.1.zip
   creating: setuptools-44.1.1/
   creating: setuptools-44.1.1/setuptools.egg-info/
   creating: setuptools-44.1.1/setuptools/
   creating: setuptools-44.1.1/docs/
   creating: setuptools-44.1.1/pkg_resources/
  inflating: setuptools-44.1.1/MANIFEST.in  
  inflating: setuptools-44.1.1/setup.py  
  inflating: setuptools-44.1.1/setup.cfg  
  inflating: setuptools-44.1.1/README.rst  
  inflating: setuptools-44.1.1/CHANGES.rst  
  inflating: setuptools-44.1.1/LICENSE  
  inflating: setuptools-44.1.1/towncrier_template.rst  
  inflating: setuptools-44.1.1/easy_install.py  
  inflating: setuptools-44.1.1/pavement.py  
  inflating: setuptools-44.1.1/launcher.c  
  inflating: setuptools-44.1.1/bootstrap.py  
  inflating: setuptools-44.1.1/PKG-INFO  
  inflating: setuptools-44.1.1/pytest.ini  
  inflating: setuptools-44.1.1/conftest.py  
  inflating: setuptools-44.1.1/msvc-build-launcher.cmd  
  inflating: setuptools-44.1.1/tox.ini  
  inflating: setuptools-44.1.1/setuptools.egg-info/SOURCES.txt  
  inflating: setuptools-44.1.1/setuptools.egg-info/dependency_links.txt  
  inflating: setuptools-44.1.1/setuptools.egg-info/zip-safe  
  inflating: setuptools-44.1.1/setuptools.egg-info/top_level.txt  
  inflating: setuptools-44.1.1/setuptools.egg-info/requires.txt  
  inflating: setuptools-44.1.1/setuptools.egg-info/PKG-INFO  
  inflating: setuptools-44.1.1/setuptools.egg-info/entry_points.txt  
   creating: setuptools-44.1.1/setuptools/command/
   creating: setuptools-44.1.1/setuptools/_vendor/
   creating: setuptools-44.1.1/setuptools/extern/
   creating: setuptools-44.1.1/setuptools/tests/
  inflating: setuptools-44.1.1/setuptools/package_index.py  
  inflating: setuptools-44.1.1/setuptools/cli.exe  
  inflating: setuptools-44.1.1/setuptools/py27compat.py  
  inflating: setuptools-44.1.1/setuptools/windows_support.py  
  inflating: setuptools-44.1.1/setuptools/installer.py  
  inflating: setuptools-44.1.1/setuptools/cli-64.exe  
  inflating: setuptools-44.1.1/setuptools/script.tmpl  
  inflating: setuptools-44.1.1/setuptools/msvc.py  
  inflating: setuptools-44.1.1/setuptools/sandbox.py  
  inflating: setuptools-44.1.1/setuptools/extension.py  
  inflating: setuptools-44.1.1/setuptools/dep_util.py  
  inflating: setuptools-44.1.1/setuptools/script (dev).tmpl  
  inflating: setuptools-44.1.1/setuptools/cli-32.exe  
  inflating: setuptools-44.1.1/setuptools/monkey.py  
  inflating: setuptools-44.1.1/setuptools/build_meta.py  
  inflating: setuptools-44.1.1/setuptools/py33compat.py  
  inflating: setuptools-44.1.1/setuptools/depends.py  
  inflating: setuptools-44.1.1/setuptools/launch.py  
  inflating: setuptools-44.1.1/setuptools/dist.py  
  inflating: setuptools-44.1.1/setuptools/site-patch.py  
  inflating: setuptools-44.1.1/setuptools/namespaces.py  
  inflating: setuptools-44.1.1/setuptools/_imp.py  
  inflating: setuptools-44.1.1/setuptools/wheel.py  
  inflating: setuptools-44.1.1/setuptools/__init__.py  
  inflating: setuptools-44.1.1/setuptools/ssl_support.py  
  inflating: setuptools-44.1.1/setuptools/glob.py  
  inflating: setuptools-44.1.1/setuptools/config.py  
  inflating: setuptools-44.1.1/setuptools/gui.exe  
  inflating: setuptools-44.1.1/setuptools/unicode_utils.py  
  inflating: setuptools-44.1.1/setuptools/gui-64.exe  
  inflating: setuptools-44.1.1/setuptools/py34compat.py  
  inflating: setuptools-44.1.1/setuptools/gui-32.exe  
  inflating: setuptools-44.1.1/setuptools/archive_util.py  
  inflating: setuptools-44.1.1/setuptools/lib2to3_ex.py  
  inflating: setuptools-44.1.1/setuptools/_deprecation_warning.py  
  inflating: setuptools-44.1.1/setuptools/version.py  
  inflating: setuptools-44.1.1/setuptools/errors.py  
  inflating: setuptools-44.1.1/setuptools/py31compat.py  
  inflating: setuptools-44.1.1/setuptools/command/rotate.py  
  inflating: setuptools-44.1.1/setuptools/command/launcher manifest.xml  
  inflating: setuptools-44.1.1/setuptools/command/install_scripts.py  
  inflating: setuptools-44.1.1/setuptools/command/sdist.py  
  inflating: setuptools-44.1.1/setuptools/command/build_clib.py  
  inflating: setuptools-44.1.1/setuptools/command/saveopts.py  
  inflating: setuptools-44.1.1/setuptools/command/register.py  
  inflating: setuptools-44.1.1/setuptools/command/install.py  
  inflating: setuptools-44.1.1/setuptools/command/build_py.py  
  inflating: setuptools-44.1.1/setuptools/command/egg_info.py  
  inflating: setuptools-44.1.1/setuptools/command/develop.py  
  inflating: setuptools-44.1.1/setuptools/command/alias.py  
  inflating: setuptools-44.1.1/setuptools/command/easy_install.py  
  inflating: setuptools-44.1.1/setuptools/command/py36compat.py  
  inflating: setuptools-44.1.1/setuptools/command/__init__.py  
  inflating: setuptools-44.1.1/setuptools/command/setopt.py  
  inflating: setuptools-44.1.1/setuptools/command/bdist_wininst.py  
  inflating: setuptools-44.1.1/setuptools/command/bdist_rpm.py  
  inflating: setuptools-44.1.1/setuptools/command/install_lib.py  
  inflating: setuptools-44.1.1/setuptools/command/install_egg_info.py  
  inflating: setuptools-44.1.1/setuptools/command/dist_info.py  
  inflating: setuptools-44.1.1/setuptools/command/bdist_egg.py  
  inflating: setuptools-44.1.1/setuptools/command/upload.py  
  inflating: setuptools-44.1.1/setuptools/command/build_ext.py  
  inflating: setuptools-44.1.1/setuptools/command/upload_docs.py  
  inflating: setuptools-44.1.1/setuptools/command/test.py  
   creating: setuptools-44.1.1/setuptools/_vendor/packaging/
  inflating: setuptools-44.1.1/setuptools/_vendor/ordered_set.py  
  inflating: setuptools-44.1.1/setuptools/_vendor/vendored.txt  
  inflating: setuptools-44.1.1/setuptools/_vendor/pyparsing.py  
  inflating: setuptools-44.1.1/setuptools/_vendor/six.py  
  inflating: setuptools-44.1.1/setuptools/_vendor/__init__.py  
  inflating: setuptools-44.1.1/setuptools/_vendor/packaging/utils.py  
  inflating: setuptools-44.1.1/setuptools/_vendor/packaging/_structures.py  
  inflating: setuptools-44.1.1/setuptools/_vendor/packaging/markers.py  
  inflating: setuptools-44.1.1/setuptools/_vendor/packaging/_compat.py  
  inflating: setuptools-44.1.1/setuptools/_vendor/packaging/specifiers.py  
  inflating: setuptools-44.1.1/setuptools/_vendor/packaging/tags.py  
  inflating: setuptools-44.1.1/setuptools/_vendor/packaging/__about__.py  
  inflating: setuptools-44.1.1/setuptools/_vendor/packaging/__init__.py  
  inflating: setuptools-44.1.1/setuptools/_vendor/packaging/requirements.py  
  inflating: setuptools-44.1.1/setuptools/_vendor/packaging/version.py  
  inflating: setuptools-44.1.1/setuptools/extern/__init__.py  
   creating: setuptools-44.1.1/setuptools/tests/indexes/
  inflating: setuptools-44.1.1/setuptools/tests/test_upload.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_wheel.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_build_meta.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_sdist.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_develop.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_glob.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_build_ext.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_setuptools.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_dist.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_msvc.py  
  inflating: setuptools-44.1.1/setuptools/tests/environment.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_dep_util.py  
  inflating: setuptools-44.1.1/setuptools/tests/script-with-bom.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_dist_info.py  
  inflating: setuptools-44.1.1/setuptools/tests/text.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_easy_install.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_packageindex.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_integration.py  
  inflating: setuptools-44.1.1/setuptools/tests/server.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_egg_info.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_config.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_windows_wrappers.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_unicode_utils.py  
  inflating: setuptools-44.1.1/setuptools/tests/namespaces.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_install_scripts.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_archive_util.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_manifest.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_sandbox.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_test.py  
  inflating: setuptools-44.1.1/setuptools/tests/__init__.py  
  inflating: setuptools-44.1.1/setuptools/tests/mod_with_constant.py  
  inflating: setuptools-44.1.1/setuptools/tests/contexts.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_bdist_egg.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_build_py.py  
  inflating: setuptools-44.1.1/setuptools/tests/files.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_build_clib.py  
  inflating: setuptools-44.1.1/setuptools/tests/textwrap.py  
  inflating: setuptools-44.1.1/setuptools/tests/fixtures.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_upload_docs.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_depends.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_setopt.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_virtualenv.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_namespaces.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_register.py  
  inflating: setuptools-44.1.1/setuptools/tests/test_find_packages.py  
   creating: setuptools-44.1.1/setuptools/tests/indexes/test_links_priority/
   creating: setuptools-44.1.1/setuptools/tests/indexes/test_links_priority/simple/
  inflating: setuptools-44.1.1/setuptools/tests/indexes/test_links_priority/external.html  
   creating: setuptools-44.1.1/setuptools/tests/indexes/test_links_priority/simple/foobar/
  inflating: setuptools-44.1.1/setuptools/tests/indexes/test_links_priority/simple/foobar/index.html  
   creating: setuptools-44.1.1/docs/_templates/
   creating: setuptools-44.1.1/docs/_theme/
  inflating: setuptools-44.1.1/docs/setuptools.txt  
  inflating: setuptools-44.1.1/docs/index.txt  
  inflating: setuptools-44.1.1/docs/requirements.txt  
  inflating: setuptools-44.1.1/docs/formats.txt  
  inflating: setuptools-44.1.1/docs/pkg_resources.txt  
  inflating: setuptools-44.1.1/docs/Makefile  
  inflating: setuptools-44.1.1/docs/history.txt  
  inflating: setuptools-44.1.1/docs/roadmap.txt  
  inflating: setuptools-44.1.1/docs/releases.txt  
  inflating: setuptools-44.1.1/docs/python3.txt  
  inflating: setuptools-44.1.1/docs/developer-guide.txt  
  inflating: setuptools-44.1.1/docs/development.txt  
  inflating: setuptools-44.1.1/docs/conf.py  
  inflating: setuptools-44.1.1/docs/easy_install.txt  
  inflating: setuptools-44.1.1/docs/_templates/indexsidebar.html  
   creating: setuptools-44.1.1/docs/_theme/nature/
   creating: setuptools-44.1.1/docs/_theme/nature/static/
  inflating: setuptools-44.1.1/docs/_theme/nature/theme.conf  
  inflating: setuptools-44.1.1/docs/_theme/nature/static/pygments.css  
  inflating: setuptools-44.1.1/docs/_theme/nature/static/nature.css_t  
   creating: setuptools-44.1.1/pkg_resources/_vendor/
   creating: setuptools-44.1.1/pkg_resources/extern/
   creating: setuptools-44.1.1/pkg_resources/tests/
  inflating: setuptools-44.1.1/pkg_resources/api_tests.txt  
  inflating: setuptools-44.1.1/pkg_resources/__init__.py  
  inflating: setuptools-44.1.1/pkg_resources/py31compat.py  
   creating: setuptools-44.1.1/pkg_resources/_vendor/packaging/
  inflating: setuptools-44.1.1/pkg_resources/_vendor/vendored.txt  
  inflating: setuptools-44.1.1/pkg_resources/_vendor/pyparsing.py  
  inflating: setuptools-44.1.1/pkg_resources/_vendor/six.py  
  inflating: setuptools-44.1.1/pkg_resources/_vendor/__init__.py  
  inflating: setuptools-44.1.1/pkg_resources/_vendor/appdirs.py  
  inflating: setuptools-44.1.1/pkg_resources/_vendor/packaging/utils.py  
  inflating: setuptools-44.1.1/pkg_resources/_vendor/packaging/_structures.py  
  inflating: setuptools-44.1.1/pkg_resources/_vendor/packaging/markers.py  
  inflating: setuptools-44.1.1/pkg_resources/_vendor/packaging/_compat.py  
  inflating: setuptools-44.1.1/pkg_resources/_vendor/packaging/specifiers.py  
  inflating: setuptools-44.1.1/pkg_resources/_vendor/packaging/__about__.py  
  inflating: setuptools-44.1.1/pkg_resources/_vendor/packaging/__init__.py  
  inflating: setuptools-44.1.1/pkg_resources/_vendor/packaging/requirements.py  
  inflating: setuptools-44.1.1/pkg_resources/_vendor/packaging/version.py  
  inflating: setuptools-44.1.1/pkg_resources/extern/__init__.py  
   creating: setuptools-44.1.1/pkg_resources/tests/data/
  inflating: setuptools-44.1.1/pkg_resources/tests/test_resources.py  
  inflating: setuptools-44.1.1/pkg_resources/tests/test_working_set.py  
  inflating: setuptools-44.1.1/pkg_resources/tests/test_find_distributions.py  
  inflating: setuptools-44.1.1/pkg_resources/tests/__init__.py  
  inflating: setuptools-44.1.1/pkg_resources/tests/test_markers.py  
  inflating: setuptools-44.1.1/pkg_resources/tests/test_pkg_resources.py  
   creating: setuptools-44.1.1/pkg_resources/tests/data/my-test-package-source/
   creating: setuptools-44.1.1/pkg_resources/tests/data/my-test-package_unpacked-egg/
  inflating: setuptools-44.1.1/pkg_resources/tests/data/my-test-package-source/setup.py  
   creating: setuptools-44.1.1/pkg_resources/tests/data/my-test-package_unpacked-egg/my_test_package-1.0-py3.7.egg/
   creating: setuptools-44.1.1/pkg_resources/tests/data/my-test-package_unpacked-egg/my_test_package-1.0-py3.7.egg/EGG-INFO/
  inflating: setuptools-44.1.1/pkg_resources/tests/data/my-test-package_unpacked-egg/my_test_package-1.0-py3.7.egg/EGG-INFO/SOURCES.txt  
  inflating: setuptools-44.1.1/pkg_resources/tests/data/my-test-package_unpacked-egg/my_test_package-1.0-py3.7.egg/EGG-INFO/dependency_links.txt  
  inflating: setuptools-44.1.1/pkg_resources/tests/data/my-test-package_unpacked-egg/my_test_package-1.0-py3.7.egg/EGG-INFO/top_level.txt  
sudo -u fink-bld [ENV] sh -c /tmp/fink.qXiSS
echo Skipping compile stage
Skipping compile stage
/bin/rm -rf /opt/sw/src/fink.build/root-setuptools-tng-py27-44.1.1-1
/bin/mkdir -p /opt/sw/src/fink.build/root-setuptools-tng-py27-44.1.1-1/opt/sw
/bin/mkdir -p /opt/sw/src/fink.build/root-setuptools-tng-py27-44.1.1-1/DEBIAN
/usr/sbin/chown -R fink-bld:fink-bld /opt/sw/src/fink.build/root-setuptools-tng-py27-44.1.1-1
sudo -u fink-bld [ENV] sh -c /tmp/fink.5_zLT
/opt/sw/bin/python2.7 setup.py install --root=/opt/sw/src/fink.build/root-setuptools-tng-py27-44.1.1-1 --single-version-externally-managed
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    import setuptools
  File "/opt/sw/src/fink.build/setuptools-tng-py27-44.1.1-1/setuptools-44.1.1/setuptools/__init__.py", line 20, in <module>
    from setuptools.dist import Distribution, Feature
  File "/opt/sw/src/fink.build/setuptools-tng-py27-44.1.1-1/setuptools-44.1.1/setuptools/dist.py", line 36, in <module>
    from setuptools import windows_support
  File "/opt/sw/src/fink.build/setuptools-tng-py27-44.1.1-1/setuptools-44.1.1/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/opt/sw/lib/python2.7/ctypes/__init__.py", line 556, in <module>
    _reset_cache()
  File "/opt/sw/lib/python2.7/ctypes/__init__.py", line 276, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)
MemoryError
### execution of /opt/sw/bin/python2.7 failed, exit code 1
### execution of /tmp/fink.5_zLT failed, exit code 1
Removing runtime build-lock...
Removing build-lock package...
/opt/sw/bin/dpkg-lockwait -r fink-buildlock-setuptools-tng-py27-44.1.1-1
(Reading database ... 74280 files and directories currently installed.)
Removing fink-buildlock-setuptools-tng-py27-44.1.1-1 (2023.01.30-20.36.26) ...
Failed: phase installing: setuptools-tng-py27-44.1.1-1 failed
```

```
Package manager version: 0.45.99.git
Distribution version: selfupdate-rsync Mon Jan 30 14:46:16 2023, 12.0, arm64
Trees: local/main remote/dak180 stable/main local/injected
Xcode.app: 14.2
Xcode command-line tools: 14.2.0.0.1.1668646533
Max. Fink build jobs:  1
```

**Comment by TheSin-** [comment]
the MemoryErrors from the 6 tests for arm64 are not going to be tribal to fix, specially since 27 is EOL

**Comment by TheSin-** [comment]
Just ran into this one so I guess I'll see if I can figure it out, but this will be a fix to python27 for sure.

**Comment by TheSin-** [comment]
python27-2.7.18-7 which was just pushed will fix this.
